//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.20.0
//     from Assets/Controles/MisAccionesDeEntrada.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Controles/MisAccionesDeEntrada.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @MisAccionesDeEntrada: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @MisAccionesDeEntrada()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""MisAccionesDeEntrada"",
    ""maps"": [
        {
            ""name"": ""MiMapaDeAcciones"",
            ""id"": ""dc7c4551-f73d-487a-9aa0-e1544d92f78f"",
            ""actions"": [
                {
                    ""name"": ""CaminarAdelante"",
                    ""type"": ""Button"",
                    ""id"": ""258da517-774a-4e1c-a05b-14ffc8d41816"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""CaminarAtras"",
                    ""type"": ""Button"",
                    ""id"": ""6c630db2-6c62-4196-8bcf-d4d7b80a3555"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Agachar"",
                    ""type"": ""Button"",
                    ""id"": ""3f5f47de-15c3-414c-aa96-07662521e186"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Saltar"",
                    ""type"": ""Button"",
                    ""id"": ""fa7949fe-9d7a-42e5-8dee-86b1fe58db0e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""Correr"",
                    ""type"": ""Button"",
                    ""id"": ""69dd0976-4d18-406b-8c7e-acf2f6650088"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a1bacb47-7053-4acd-a4a2-a7e89c3ea7a5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CaminarAdelante"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""adf74719-5930-4e40-88c3-5f608c4ac01a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CaminarAtras"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3d034b5-85ea-4357-b14c-6a1ca087108e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Agachar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d68a5f0e-0e15-4b1e-a3f8-2c35a1b0364f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Saltar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fbef3fb-f26d-463e-ac69-70c27daa3438"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Correr"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MiMapaDeAcciones
        m_MiMapaDeAcciones = asset.FindActionMap("MiMapaDeAcciones", throwIfNotFound: true);
        m_MiMapaDeAcciones_CaminarAdelante = m_MiMapaDeAcciones.FindAction("CaminarAdelante", throwIfNotFound: true);
        m_MiMapaDeAcciones_CaminarAtras = m_MiMapaDeAcciones.FindAction("CaminarAtras", throwIfNotFound: true);
        m_MiMapaDeAcciones_Agachar = m_MiMapaDeAcciones.FindAction("Agachar", throwIfNotFound: true);
        m_MiMapaDeAcciones_Saltar = m_MiMapaDeAcciones.FindAction("Saltar", throwIfNotFound: true);
        m_MiMapaDeAcciones_Correr = m_MiMapaDeAcciones.FindAction("Correr", throwIfNotFound: true);
    }

    ~@MisAccionesDeEntrada()
    {
        UnityEngine.Debug.Assert(!m_MiMapaDeAcciones.enabled, "This will cause a leak and performance issues, MisAccionesDeEntrada.MiMapaDeAcciones.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MiMapaDeAcciones
    private readonly InputActionMap m_MiMapaDeAcciones;
    private List<IMiMapaDeAccionesActions> m_MiMapaDeAccionesActionsCallbackInterfaces = new List<IMiMapaDeAccionesActions>();
    private readonly InputAction m_MiMapaDeAcciones_CaminarAdelante;
    private readonly InputAction m_MiMapaDeAcciones_CaminarAtras;
    private readonly InputAction m_MiMapaDeAcciones_Agachar;
    private readonly InputAction m_MiMapaDeAcciones_Saltar;
    private readonly InputAction m_MiMapaDeAcciones_Correr;
    /// <summary>
    /// Provides access to input actions defined in input action map "MiMapaDeAcciones".
    /// </summary>
    public struct MiMapaDeAccionesActions
    {
        private @MisAccionesDeEntrada m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public MiMapaDeAccionesActions(@MisAccionesDeEntrada wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "MiMapaDeAcciones/CaminarAdelante".
        /// </summary>
        public InputAction @CaminarAdelante => m_Wrapper.m_MiMapaDeAcciones_CaminarAdelante;
        /// <summary>
        /// Provides access to the underlying input action "MiMapaDeAcciones/CaminarAtras".
        /// </summary>
        public InputAction @CaminarAtras => m_Wrapper.m_MiMapaDeAcciones_CaminarAtras;
        /// <summary>
        /// Provides access to the underlying input action "MiMapaDeAcciones/Agachar".
        /// </summary>
        public InputAction @Agachar => m_Wrapper.m_MiMapaDeAcciones_Agachar;
        /// <summary>
        /// Provides access to the underlying input action "MiMapaDeAcciones/Saltar".
        /// </summary>
        public InputAction @Saltar => m_Wrapper.m_MiMapaDeAcciones_Saltar;
        /// <summary>
        /// Provides access to the underlying input action "MiMapaDeAcciones/Correr".
        /// </summary>
        public InputAction @Correr => m_Wrapper.m_MiMapaDeAcciones_Correr;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_MiMapaDeAcciones; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="MiMapaDeAccionesActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(MiMapaDeAccionesActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="MiMapaDeAccionesActions" />
        public void AddCallbacks(IMiMapaDeAccionesActions instance)
        {
            if (instance == null || m_Wrapper.m_MiMapaDeAccionesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MiMapaDeAccionesActionsCallbackInterfaces.Add(instance);
            @CaminarAdelante.started += instance.OnCaminarAdelante;
            @CaminarAdelante.performed += instance.OnCaminarAdelante;
            @CaminarAdelante.canceled += instance.OnCaminarAdelante;
            @CaminarAtras.started += instance.OnCaminarAtras;
            @CaminarAtras.performed += instance.OnCaminarAtras;
            @CaminarAtras.canceled += instance.OnCaminarAtras;
            @Agachar.started += instance.OnAgachar;
            @Agachar.performed += instance.OnAgachar;
            @Agachar.canceled += instance.OnAgachar;
            @Saltar.started += instance.OnSaltar;
            @Saltar.performed += instance.OnSaltar;
            @Saltar.canceled += instance.OnSaltar;
            @Correr.started += instance.OnCorrer;
            @Correr.performed += instance.OnCorrer;
            @Correr.canceled += instance.OnCorrer;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="MiMapaDeAccionesActions" />
        private void UnregisterCallbacks(IMiMapaDeAccionesActions instance)
        {
            @CaminarAdelante.started -= instance.OnCaminarAdelante;
            @CaminarAdelante.performed -= instance.OnCaminarAdelante;
            @CaminarAdelante.canceled -= instance.OnCaminarAdelante;
            @CaminarAtras.started -= instance.OnCaminarAtras;
            @CaminarAtras.performed -= instance.OnCaminarAtras;
            @CaminarAtras.canceled -= instance.OnCaminarAtras;
            @Agachar.started -= instance.OnAgachar;
            @Agachar.performed -= instance.OnAgachar;
            @Agachar.canceled -= instance.OnAgachar;
            @Saltar.started -= instance.OnSaltar;
            @Saltar.performed -= instance.OnSaltar;
            @Saltar.canceled -= instance.OnSaltar;
            @Correr.started -= instance.OnCorrer;
            @Correr.performed -= instance.OnCorrer;
            @Correr.canceled -= instance.OnCorrer;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MiMapaDeAccionesActions.UnregisterCallbacks(IMiMapaDeAccionesActions)" />.
        /// </summary>
        /// <seealso cref="MiMapaDeAccionesActions.UnregisterCallbacks(IMiMapaDeAccionesActions)" />
        public void RemoveCallbacks(IMiMapaDeAccionesActions instance)
        {
            if (m_Wrapper.m_MiMapaDeAccionesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="MiMapaDeAccionesActions.AddCallbacks(IMiMapaDeAccionesActions)" />
        /// <seealso cref="MiMapaDeAccionesActions.RemoveCallbacks(IMiMapaDeAccionesActions)" />
        /// <seealso cref="MiMapaDeAccionesActions.UnregisterCallbacks(IMiMapaDeAccionesActions)" />
        public void SetCallbacks(IMiMapaDeAccionesActions instance)
        {
            foreach (var item in m_Wrapper.m_MiMapaDeAccionesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MiMapaDeAccionesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="MiMapaDeAccionesActions" /> instance referencing this action map.
    /// </summary>
    public MiMapaDeAccionesActions @MiMapaDeAcciones => new MiMapaDeAccionesActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "MiMapaDeAcciones" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="MiMapaDeAccionesActions.AddCallbacks(IMiMapaDeAccionesActions)" />
    /// <seealso cref="MiMapaDeAccionesActions.RemoveCallbacks(IMiMapaDeAccionesActions)" />
    public interface IMiMapaDeAccionesActions
    {
        /// <summary>
        /// Method invoked when associated input action "CaminarAdelante" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCaminarAdelante(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CaminarAtras" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCaminarAtras(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Agachar" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAgachar(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Saltar" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSaltar(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Correr" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCorrer(InputAction.CallbackContext context);
    }
}
